version: "3.3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    ports:
      - "8081:8080"
    volumes:
      - ./data:/data
      - ./config:/config
    restart: always